language: c

sudo: required

env:
  matrix:
  - BUILD_TYPE=astyle
  - BUILD_TYPE=cppcheck
  - BUILD_TYPE=ad9361_linux
  - BUILD_TYPE=ad9361_generic
  - BUILD_TYPE=drivers

script:
  - ./ci/travis/run_build.sh
