language: c

sudo: required

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./CI/travis/before_install_darwin ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./CI/travis/before_install_linux ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -C ${TRAVIS_BUILD_DIR}/ad9361/sw/ -f Makefile.linux ; fi
  - make -C ${TRAVIS_BUILD_DIR}/ad9361/sw/ -f Makefile.generic
  - cppcheck --quiet --force --error-exitcode=1 .
